#**C4.5**

##**Install chefboost and other components**

In [1]:
!pip install chefboost
from chefboost import Chefboost as chef
from chefboost.training import Training
import pandas as pd

Requirement already satisfied: chefboost in c:\users\asus\anaconda3\lib\site-packages (0.0.16)
Requirement already satisfied: pandas>=0.22.0 in c:\users\asus\anaconda3\lib\site-packages (from chefboost) (1.3.4)
Requirement already satisfied: psutil>=5.4.3 in c:\users\asus\anaconda3\lib\site-packages (from chefboost) (5.8.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\asus\anaconda3\lib\site-packages (from chefboost) (1.20.3)
Requirement already satisfied: tqdm>=4.30.0 in c:\users\asus\anaconda3\lib\site-packages (from chefboost) (4.62.3)
Requirement already satisfied: pytz>=2017.3 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=0.22.0->chefboost) (2021.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\asus\anaconda3\lib\site-packages (from pandas>=0.22.0->chefboost) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.22.0->chefboost) (1.16.0)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from tqdm>=4.30.0->chefboost) (0.4.4)

In [56]:
#Define the dataframes
df = pd.read_csv('Data2018and2017(1).csv')
df2 = pd.read_csv('Data2016.csv')
df

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
0,Yes,Fit,None,87,88,88,56,86,90,Passed
1,Yes,Fit,None,90,92,98,70,90,89,Passed
2,Yes,Fit,None,79,70,67,54,86,89,Passed
3,Yes,Fit,None,75,70,70,35,71,83,Failed
4,Yes,Fit,None,80,69,70,0,80,79,Failed
5,Yes,Fit,U_Treatment,89,90,88,30,95,45,Failed
6,Yes,Fit,None,75,78,76,66,78,89,Passed
7,Yes,Not_Fit,U_Treatment,35,40,38,0,50,90,Failed
8,Yes,Fit,None,75,75,79,55,70,93,Passed
9,No,Fit,None,90,95,95,75,90,89,Passed
10,Yes,Fit,None,80,75,76,55,80,75,Passed
11,Yes,Fit,None,88,88,92,65,88,70,Failed
12,Yes,Fit,None,0,0,0,0,0,65,Failed
13,Yes,Fit,None,90,90,95,68,68,75,Failed
14,Yes,Fit,U_Treatment,78,88,90,60,87,75,Passed
15,Yes,Fit,None,75,78,83,68,80,80,Passed
16,Yes,Fit,None,75,78,85,40,70,76,Passed
17,Yes,Fit,None,90,95,85,71,89,90,Passed
18,Yes,Fit,None,0,0,0,0,0,0,Failed
19,Yes,Fit,None,78,90,89,51,80,93,Passed
20,Yes,Not_Fit,U_Treatment,70,65,74,40,71,85,Failed
21,Yes,Fit,None,90,88,88,70,80,83,Passed
22,Yes,Fit,None,80,78,78,55,68,83,Failed
23,Yes,Fit,None,90,89,90,70,85,88,Passed
24,Yes,Fit,None,88,74,80,60,76,90,Passed
25,Yes,Fit,None,85,85,90,55,89,88,Passed
26,Yes,Fit,None,87,74,88,68,85,82,Passed
27,Yes,Fit,None,90,75,89,55,90,80,Passed
28,Yes,Fit,None,0,0,0,0,0,0,Failed
29,Yes,Not_Fit,None,79,88,78,60,74,75,Passed
30,Yes,Fit,None,90,85,88,70,88,90,Passed
31,Yes,Fit,None,88,75,90,65,76,85,Passed

In [57]:
df2

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
0,Yes,Fit,None,75,78,83,68,80,80,Passed
1,Yes,Fit,None,90,95,85,71,89,90,Passed
2,Yes,Fit,None,87,88,88,56,86,90,Passed
3,Yes,Not_Fit,None,78,90,89,51,80,93,Passed
4,Yes,Fit,None,80,78,78,55,70,83,Passed
5,Yes,Fit,None,81,88,80,56,80,75,Passed
6,Yes,Not_Fit,U_Treatment,88,88,92,65,88,70,Failed
7,Yes,Fit,None,89,89,88,70,80,83,Passed
8,Yes,Fit,None,98,78,78,60,74,85,Passed
9,Yes,Fit,None,74,80,75,0,78,0,Failed
10,Yes,Fit,None,71,78,76,66,78,89,Passed
11,Yes,Fit,None,86,88,88,70,80,83,Passed
12,Yes,Fit,None,81,90,90,71,80,90,Passed
13,Yes,Fit,None,79,70,67,54,86,89,Passed
14,Yes,Fit,None,80,78,76,66,78,89,Passed
15,Yes,Not_Fit,None,77,65,58,34,78,80,Failed
16,Yes,Fit,None,80,88,78,60,74,75,Passed
17,Yes,Fit,None,78,70,70,40,71,83,Passed
18,Yes,Fit,None,87,78,76,66,78,89,Passed
19,Yes,Fit,None,68,88,90,60,87,75,Passed
20,Yes,Fit,None,88,74,89,65,76,77,Passed
21,Yes,Fit,None,71,74,80,60,76,90,Passed
22,Yes,Fit,None,88,75,90,65,76,85,Passed
23,Yes,Fit,None,75,40,70,40,50,90,Passed

##**Configuring the chefboost**

In [3]:
id3 = {'algorithm': 'ID3'}
c45 = {'algorithm': 'C4.5'}

##**Accuracy**

In [4]:
model = chef.fit(df.copy(), c45)

[INFO]:  1 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
-------------------------
finished in  2.9277329444885254  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  100.0 % on  32  instances
Labels:  ['Passed' 'Failed']
Confusion matrix:  [[21, 0], [0, 11]]
Precision:  100.0 %, Recall:  100.0 %, F1:  100.0 %

In [5]:
#Testing it on the Data from 2016 to get the accuracy
for index, instance in df2.iterrows():
  prediction = chef.predict(model, instance)
  actual = instance['Decision']
  
  if actual == prediction:
    classified = True
  else:
    classified = False
    print("*", end="")

  print(index,'Actual: ',actual, ' - ', 'C4.5 Prediction: ', prediction)

0 Actual:  Passed  -  C4.5 Prediction:  Passed
1 Actual:  Passed  -  C4.5 Prediction:  Passed
2 Actual:  Passed  -  C4.5 Prediction:  Passed
3 Actual:  Passed  -  C4.5 Prediction:  Passed
4 Actual:  Passed  -  C4.5 Prediction:  Passed
5 Actual:  Passed  -  C4.5 Prediction:  Passed
6 Actual:  Failed  -  C4.5 Prediction:  Failed
7 Actual:  Passed  -  C4.5 Prediction:  Passed
8 Actual:  Passed  -  C4.5 Prediction:  Passed
9 Actual:  Failed  -  C4.5 Prediction:  Failed
10 Actual:  Passed  -  C4.5 Prediction:  Passed
11 Actual:  Passed  -  C4.5 Prediction:  Passed
12 Actual:  Passed  -  C4.5 Prediction:  Passed
13 Actual:  Passed  -  C4.5 Prediction:  Passed
14 Actual:  Passed  -  C4.5 Prediction:  Passed
15 Actual:  Failed  -  C4.5 Prediction:  Failed
16 Actual:  Passed  -  C4.5 Prediction:  Passed
17 Actual:  Passed  -  C4.5 Prediction:  Passed
18 Actual:  Passed  -  C4.5 Prediction:  Passed
*19 Actual:  Passed  -  C4.5 Prediction:  Failed
20 Actual:  Passed  -  C4.5 Prediction:  Passed
21 Actual:  Passed  -  C4.5 Prediction:  Passed
22 Actual:  Passed  -  C4.5 Prediction:  Passed
*23 Actual:  Passed  -  C4.5 Prediction:  Failed

##**Constructing the Tree**

###**Split 1**

In [6]:
#The Information Gain
info_gain = Training.findGains(df, id3)
'Information Gain: ', info_gain

('Information Gain: ',
 {'gains': {'Administration': 0.019369074918754836,
   'Medical_certificate': 0.03247302707814907,
   'Medical_history': 0.071721809341674,
   'Cooper_test': 0.2835645200282194,
   'Push_up': 0.3545143749299422,
   'Sit_up': 0.30495414535870313,
   'Pull_up': 0.4328077328319255,
   'Shuttle_run': 0.3545143749299422,
   'MI': 0.2835645200282194},
  'entropy': 0.9283620723948678})

In [7]:
#Finding the gain ratio for first split
first_split = Training.findGains(df, c45)
'Gain Ratio: ', first_split

('Gain Ratio: ',
 {'gains': {'Administration': 0.09654496320441294,
   'Medical_certificate': 0.07234483434083035,
   'Medical_history': 0.1319472055962605,
   'Cooper_test': 0.4535128254302994,
   'Push_up': 0.5092044412809068,
   'Sit_up': 0.375893465094984,
   'Pull_up': 0.5710780213786569,
   'Shuttle_run': 0.5092044412809068,
   'MI': 0.4535128254302994},
  'entropy': 0.9283620723948678})

In [8]:
#checking the splitting attribute label
df['Pull_up']

0      >35
1      >35
2      >35
3     <=35
4     <=35
5     <=35
6      >35
7     <=35
8      >35
9      >35
10     >35
11     >35
12    <=35
13     >35
14     >35
15     >35
16     >35
17     >35
18    <=35
19     >35
20     >35
21     >35
22     >35
23     >35
24     >35
25     >35
26     >35
27     >35
28    <=35
29     >35
30     >35
31     >35
Name: Pull_up, dtype: object

In [9]:
df[df['Pull_up']=='>35']

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
0,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
1,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
2,Yes,Fit,None,>70,>69,<=74,>35,>68,>70,Passed
6,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
8,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
9,No,Fit,None,>70,>69,>74,>35,>68,>70,Passed
10,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
11,Yes,Fit,None,>70,>69,>74,>35,>68,<=70,Failed
13,Yes,Fit,None,>70,>69,>74,>35,<=68,>70,Failed
14,Yes,Fit,U_Treatment,>70,>69,>74,>35,>68,>70,Passed
15,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
16,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
17,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
19,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
20,Yes,Not_Fit,U_Treatment,<=70,<=69,<=74,>35,>68,>70,Failed
21,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
22,Yes,Fit,None,>70,>69,>74,>35,<=68,>70,Failed
23,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
24,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
25,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
26,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
27,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
29,Yes,Not_Fit,None,>70,>69,>74,>35,>68,>70,Passed
30,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
31,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed

In [10]:
df[df['Pull_up']=='<=35']

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
3,Yes,Fit,None,>70,>69,<=74,<=35,>68,>70,Failed
4,Yes,Fit,None,>70,<=69,<=74,<=35,>68,>70,Failed
5,Yes,Fit,U_Treatment,>70,>69,>74,<=35,>68,<=70,Failed
7,Yes,Not_Fit,U_Treatment,<=70,<=69,<=74,<=35,<=68,>70,Failed
12,Yes,Fit,None,<=70,<=69,<=74,<=35,<=68,<=70,Failed
18,Yes,Fit,None,<=70,<=69,<=74,<=35,<=68,<=70,Failed
28,Yes,Fit,None,<=70,<=69,<=74,<=35,<=68,<=70,Failed

In [11]:
second_split = Training.findGains(df[df['Pull_up']=='>35'].drop(columns=['Pull_up']), c45)
second_split

{'gains': {'Administration': 0.04246125265988998,
  'Medical_certificate': 0.10037946280671267,
  'Medical_history': 0.10037946280671267,
  'Cooper_test': 0.4642646120576809,
  'Push_up': 0.4642646120576809,
  'Sit_up': 0.10037946280671267,
  'Shuttle_run': 0.6021673823562843,
  'MI': 0.4642646120576809},
 'entropy': 0.6343095546405662}

In [12]:
second_split2 = Training.findGains(df[df['Pull_up']=='<=35'].drop(columns=['Pull_up']), c45)
second_split2

{'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Cooper_test': 0.0,
  'Push_up': 0.0,
  'Sit_up': 0.0,
  'Shuttle_run': 0.0,
  'MI': 0.0},
 'entropy': 0.0}

In [13]:
#First Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    return 'Need further research'
  else: return 'Failed'

###**Split 2**

In [14]:
#Finding the gain ratio for second split
second_split = Training.findGains(df[df['Pull_up']=='>35'].drop(columns=['Pull_up']), c45)
second_split

{'gains': {'Administration': 0.04246125265988998,
  'Medical_certificate': 0.10037946280671267,
  'Medical_history': 0.10037946280671267,
  'Cooper_test': 0.4642646120576809,
  'Push_up': 0.4642646120576809,
  'Sit_up': 0.10037946280671267,
  'Shuttle_run': 0.6021673823562843,
  'MI': 0.4642646120576809},
 'entropy': 0.6343095546405662}

In [15]:
df['Shuttle_run']

0      >68
1      >68
2      >68
3      >68
4      >68
5      >68
6      >68
7     <=68
8      >68
9      >68
10     >68
11     >68
12    <=68
13    <=68
14     >68
15     >68
16     >68
17     >68
18    <=68
19     >68
20     >68
21     >68
22    <=68
23     >68
24     >68
25     >68
26     >68
27     >68
28    <=68
29     >68
30     >68
31     >68
Name: Shuttle_run, dtype: object

In [16]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/586016150.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68']

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
0,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
1,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
2,Yes,Fit,None,>70,>69,<=74,>35,>68,>70,Passed
6,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
8,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
9,No,Fit,None,>70,>69,>74,>35,>68,>70,Passed
10,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
11,Yes,Fit,None,>70,>69,>74,>35,>68,<=70,Failed
14,Yes,Fit,U_Treatment,>70,>69,>74,>35,>68,>70,Passed
15,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
16,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
17,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
19,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
20,Yes,Not_Fit,U_Treatment,<=70,<=69,<=74,>35,>68,>70,Failed
21,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
23,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
24,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
25,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
26,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
27,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
29,Yes,Not_Fit,None,>70,>69,>74,>35,>68,>70,Passed
30,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
31,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed

In [17]:
third_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'].drop(columns=['Pull_up', 'Shuttle_run']),c45)
third_split

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2347230296.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  third_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'].drop(columns=['Pull_up', 'Shuttle_run']),c45)

{'gains': {'Administration': 0.022634930858355023,
  'Medical_certificate': 0.20433563039373695,
  'Medical_history': 0.20433563039373695,
  'Cooper_test': 0.6629836042906918,
  'Push_up': 0.6629836042906918,
  'Sit_up': 0.20433563039373695,
  'MI': 0.6629836042906918},
 'entropy': 0.4262286569981449}

In [18]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='<=68']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/893129663.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='<=68']

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
13,Yes,Fit,None,>70,>69,>74,>35,<=68,>70,Failed
22,Yes,Fit,None,>70,>69,>74,>35,<=68,>70,Failed

In [19]:
third_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='<=68'].drop(columns=['Pull_up', 'Shuttle_run']),c45)
third_split2

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/1196639779.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  third_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='<=68'].drop(columns=['Pull_up', 'Shuttle_run']),c45)

{'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Cooper_test': 0.0,
  'Push_up': 0.0,
  'Sit_up': 0.0,
  'MI': 0.0},
 'entropy': 0.0}

In [20]:
#Second Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      return 'Need further research'
    else: return 'Failed'
  else: return 'Failed'

###**Split 3**

In [21]:
#Finding the gain ratio for third split
third_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'].drop(columns=['Pull_up', 'Shuttle_run']),c45)
third_split

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2411033090.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  third_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'].drop(columns=['Pull_up', 'Shuttle_run']),c45)

{'gains': {'Administration': 0.022634930858355023,
  'Medical_certificate': 0.20433563039373695,
  'Medical_history': 0.20433563039373695,
  'Cooper_test': 0.6629836042906918,
  'Push_up': 0.6629836042906918,
  'Sit_up': 0.20433563039373695,
  'MI': 0.6629836042906918},
 'entropy': 0.4262286569981449}

In [22]:
df['Cooper_test']

0      >70
1      >70
2      >70
3      >70
4      >70
5      >70
6      >70
7     <=70
8      >70
9      >70
10     >70
11     >70
12    <=70
13     >70
14     >70
15     >70
16     >70
17     >70
18    <=70
19     >70
20    <=70
21     >70
22     >70
23     >70
24     >70
25     >70
26     >70
27     >70
28    <=70
29     >70
30     >70
31     >70
Name: Cooper_test, dtype: object

In [23]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/1924332338.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70']

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
0,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
1,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
2,Yes,Fit,None,>70,>69,<=74,>35,>68,>70,Passed
6,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
8,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
9,No,Fit,None,>70,>69,>74,>35,>68,>70,Passed
10,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
11,Yes,Fit,None,>70,>69,>74,>35,>68,<=70,Failed
14,Yes,Fit,U_Treatment,>70,>69,>74,>35,>68,>70,Passed
15,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
16,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
17,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
19,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
21,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
23,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
24,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
25,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
26,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
27,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
29,Yes,Not_Fit,None,>70,>69,>74,>35,>68,>70,Passed
30,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
31,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed

In [24]:
fourth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'].drop(columns=['Pull_up','Cooper_test','Shuttle_run']),c45)
fourth_split

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2108965694.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fourth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'].drop(columns=['Pull_up','Cooper_test','Shuttle_run']),c45)

{'gains': {'Administration': 0.011710299020778647,
  'Medical_certificate': 0.011710299020778647,
  'Medical_history': 0.011710299020778647,
  'Push_up': 0.0,
  'Sit_up': 0.011710299020778647,
  'MI': 1.0},
 'entropy': 0.26676498780302604}

In [25]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='<=70']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/1273635933.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='<=70']

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
20,Yes,Not_Fit,U_Treatment,<=70,<=69,<=74,>35,>68,>70,Failed

In [26]:
fourth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='<=70'].drop(columns=['Pull_up','Cooper_test','Shuttle_run']),c45)
fourth_split2

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/177355907.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fourth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='<=70'].drop(columns=['Pull_up','Cooper_test','Shuttle_run']),c45)

{'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Push_up': 0.0,
  'Sit_up': 0.0,
  'MI': 0.0},
 'entropy': 0.0}

In [27]:
#Third Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        return 'Need further research'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'

###**Split 4**

In [28]:
#Finding the gain ratio for fourth split
fourth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'].drop(columns=['Pull_up','Cooper_test','Shuttle_run']),c45)
fourth_split

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/334366568.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fourth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'].drop(columns=['Pull_up','Cooper_test','Shuttle_run']),c45)

{'gains': {'Administration': 0.011710299020778647,
  'Medical_certificate': 0.011710299020778647,
  'Medical_history': 0.011710299020778647,
  'Push_up': 0.0,
  'Sit_up': 0.011710299020778647,
  'MI': 1.0},
 'entropy': 0.26676498780302604}

In [29]:
df['MI']

0      >70
1      >70
2      >70
3      >70
4      >70
5     <=70
6      >70
7      >70
8      >70
9      >70
10     >70
11    <=70
12    <=70
13     >70
14     >70
15     >70
16     >70
17     >70
18    <=70
19     >70
20     >70
21     >70
22     >70
23     >70
24     >70
25     >70
26     >70
27     >70
28    <=70
29     >70
30     >70
31     >70
Name: MI, dtype: object

In [30]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/279935148.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70']

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
0,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
1,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
2,Yes,Fit,None,>70,>69,<=74,>35,>68,>70,Passed
6,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
8,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
9,No,Fit,None,>70,>69,>74,>35,>68,>70,Passed
10,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
14,Yes,Fit,U_Treatment,>70,>69,>74,>35,>68,>70,Passed
15,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
16,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
17,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
19,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
21,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
23,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
24,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
25,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
26,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
27,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
29,Yes,Not_Fit,None,>70,>69,>74,>35,>68,>70,Passed
30,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed
31,Yes,Fit,None,>70,>69,>74,>35,>68,>70,Passed

In [31]:
fifth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Push_up']),c45)
fifth_split

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/1952275513.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fifth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Push_up']),c45)

{'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Sit_up': 0.0},
 'entropy': 0.0}

In [32]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='<=70']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/489007913.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='<=70']

,Administration,Medical_certificate,Medical_history,Cooper_test,Push_up,Sit_up,Pull_up,Shuttle_run,MI,Decision
11,Yes,Fit,None,>70,>69,>74,>35,>68,<=70,Failed

In [33]:
fifth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='<=70'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Push_up']),c45)
fifth_split2

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/742919634.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fifth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='<=70'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Push_up']),c45)

{'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Sit_up': 0.0},
 'entropy': 0.0}

In [34]:
#Fourth Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        if MI>70:
          return 'Need further research'
        else: return 'Failed'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'

###**Split 5**

In [35]:
#Finding the gain ratio for fifth split
fifth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Push_up']),c45)
fifth_split

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2039430396.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  fifth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Push_up']),c45)

{'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Sit_up': 0.0},
 'entropy': 0.0}

In [36]:
df['Sit_up']

0      >74
1      >74
2     <=74
3     <=74
4     <=74
5      >74
6      >74
7     <=74
8      >74
9      >74
10     >74
11     >74
12    <=74
13     >74
14     >74
15     >74
16     >74
17     >74
18    <=74
19     >74
20    <=74
21     >74
22     >74
23     >74
24     >74
25     >74
26     >74
27     >74
28    <=74
29     >74
30     >74
31     >74
Name: Sit_up, dtype: object

In [37]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='>78']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/1224810931.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='>78']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [38]:
sixth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='>78'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Push_up']),c45)
sixth_split

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2723091743.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sixth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='>78'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Push_up']),c45)

{'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0},
 'entropy': 0}

In [39]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2940878641.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [40]:
sixth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Push_up']),c45)
sixth_split2

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/3672463844.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sixth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Push_up']),c45)

{'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0},
 'entropy': 0}

In [41]:
#Fifth Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        if MI>70:
          if Sit_up>78:
            return 'Passed'
          else: return 'Need further research'
        else: return 'Failed'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'

###**Split 6**

In [42]:
#Finding the gain ratio for sixth split
sixth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Push_up']),c45)
sixth_split2

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2036014191.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sixth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Push_up']),c45)

{'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0},
 'entropy': 0}

In [43]:
df['Medical_certificate']

0         Fit
1         Fit
2         Fit
3         Fit
4         Fit
5         Fit
6         Fit
7     Not_Fit
8         Fit
9         Fit
10        Fit
11        Fit
12        Fit
13        Fit
14        Fit
15        Fit
16        Fit
17        Fit
18        Fit
19        Fit
20    Not_Fit
21        Fit
22        Fit
23        Fit
24        Fit
25        Fit
26        Fit
27        Fit
28        Fit
29    Not_Fit
30        Fit
31        Fit
Name: Medical_certificate, dtype: object

In [44]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/3486254092.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [45]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Not_Fit']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/152858048.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Not_Fit']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [46]:
#Sixth Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        if MI>70:
          if Sit_up>78:
            return 'Passed'
          else: 
            if Medical_certificate=='Fit':
              return 'Need further research'
            elif Medical_certificate=='Not_Fit':
              return 'Passed'
        else: return 'Failed'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'

###**Split 7**

In [47]:
#Finding the gain ratio for seventh split
seventh_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Medical_certificate']),c45)
seventh_split

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2788002387.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  seventh_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Medical_certificate']),c45)

{'gains': {'Administration': 0.0, 'Medical_history': 0.0, 'Push_up': 0.0},
 'entropy': 0}

In [48]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Administration']=='Yes']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2180659303.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Administration']=='Yes']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [49]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Administration']=='No']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/278270087.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Administration']=='No']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [50]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Medical_history']=='None']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/1282912162.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Medical_history']=='None']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [51]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Medical_history']=='U_Treatment']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/876174372.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Medical_history']=='U_Treatment']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [52]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Push_up']=='>69']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/3725303923.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Push_up']=='>69']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [53]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Push_up']=='<=69']

C:\Users\ASUS\AppData\Local\Temp/ipykernel_984/2666913681.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Push_up']=='<=69']

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [54]:
#Final Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        if MI>70:
          if Sit_up>78:
            return 'Passed'
          else: 
            if Medical_certificate=='Fit':
              return 'Unable to make decision, please consider the recruits Administration, Medical history, and Push up results'
            elif Medical_certificate=='Not_Fit':
              return 'Passed'
        else: return 'Failed'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'