<a href="https://colab.research.google.com/github/Wilheim-ops/Wilheim-ops/blob/main/TugasAkhir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**C4.5**

##**Install chefboost and other components**

In [ ]:
!pip install chefboost
from chefboost import Chefboost as chef
from chefboost.training import Training
import pandas as pd

Collecting chefboost
  Downloading chefboost-0.0.16-py3-none-any.whl (26 kB)
Requirement already satisfied: tqdm>=4.30.0 in /usr/local/lib/python3.7/dist-packages (from chefboost) (4.62.3)
Requirement already satisfied: psutil>=5.4.3 in /usr/local/lib/python3.7/dist-packages (from chefboost) (5.4.8)
Requirement already satisfied: pandas>=0.22.0 in /usr/local/lib/python3.7/dist-packages (from chefboost) (1.1.5)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.7/dist-packages (from chefboost) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.22.0->chefboost) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.22.0->chefboost) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.22.0->chefboost) (1.15.0)
Installing collected packages: chefboost
Successfully installed chefboost-0.0.16

In [ ]:
#Define the dataframes
df = pd.read_csv('Data2018and2017.csv')
df2 = pd.read_csv('Data2016.csv')
df.head()

  Administration Medical_certificate Medical_history  ...  Shuttle_run  MI  Decision
0            Yes                 Fit            None  ...           86  90    Passed
1            Yes                 Fit            None  ...           90  89    Passed
2            Yes                 Fit            None  ...           86  89    Passed
3            Yes                 Fit            None  ...           71  83    Failed
4            Yes                 Fit            None  ...           80  79    Failed

[5 rows x 10 columns]

##**Configuring the chefboost**

In [ ]:
id3 = {'algorithm': 'ID3'}
c45 = {'algorithm': 'C4.5'}

##**Accuracy**

In [ ]:
model = chef.fit(df.copy(), c45)

[INFO]:  1 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
-------------------------
finished in  2.3357298374176025  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  96.875 % on  32  instances
Labels:  ['Passed' 'Failed']
Confusion matrix:  [[19, 0], [1, 12]]
Precision:  100.0 %, Recall:  95.0 %, F1:  97.4359 %

In [ ]:
#Testing it on the Data from 2016 to get the accuracy
for index, instance in df2.iterrows():
  prediction = chef.predict(model, instance)
  actual = instance['Decision']
  
  if actual == prediction:
    classified = True
  else:
    classified = False
    print("*", end="")

  print(index,'Actual: ',actual, ' - ', 'C4.5 Prediction: ', prediction)

0 Actual:  Passed  -  C4.5 Prediction:  Passed
1 Actual:  Passed  -  C4.5 Prediction:  Passed
2 Actual:  Passed  -  C4.5 Prediction:  Passed
3 Actual:  Passed  -  C4.5 Prediction:  Passed
4 Actual:  Passed  -  C4.5 Prediction:  Passed
5 Actual:  Passed  -  C4.5 Prediction:  Passed
6 Actual:  Failed  -  C4.5 Prediction:  Failed
7 Actual:  Passed  -  C4.5 Prediction:  Passed
8 Actual:  Passed  -  C4.5 Prediction:  Passed
9 Actual:  Failed  -  C4.5 Prediction:  Failed
*10 Actual:  Passed  -  C4.5 Prediction:  Failed
11 Actual:  Passed  -  C4.5 Prediction:  Passed
12 Actual:  Passed  -  C4.5 Prediction:  Passed
13 Actual:  Passed  -  C4.5 Prediction:  Passed
*14 Actual:  Passed  -  C4.5 Prediction:  Failed
15 Actual:  Failed  -  C4.5 Prediction:  Failed
16 Actual:  Passed  -  C4.5 Prediction:  Passed
17 Actual:  Passed  -  C4.5 Prediction:  Passed
*18 Actual:  Passed  -  C4.5 Prediction:  Failed
*19 Actual:  Passed  -  C4.5 Prediction:  Failed
20 Actual:  Passed  -  C4.5 Prediction:  Passed
21 Actual:  Passed  -  C4.5 Prediction:  Passed
22 Actual:  Passed  -  C4.5 Prediction:  Passed
*23 Actual:  Passed  -  C4.5 Prediction:  Failed

##**Constructing the Tree**

###**Split 1**

In [ ]:
#The Information Gain
info_gain = Training.findGains(df, id3)
'Information Gain: ', info_gain

('Information Gain: ',
 {'entropy': 0.9544340029249649,
  'gains': {'Administration': 0.02162422611524195,
   'Cooper_test': 0.25781162147924064,
   'MI': 0.25781162147924064,
   'Medical_certificate': 0.026107982407424,
   'Medical_history': 0.060337048329948975,
   'Pull_up': 0.39042767879421314,
   'Push_up': 0.3212122601251457,
   'Shuttle_run': 0.3212122601251457,
   'Sit_up': 0.2690545158050399}})

In [ ]:
#Finding the gain ratio for first split
first_split = Training.findGains(df, c45)
'Gain Ratio: ', first_split

('Gain Ratio: ',
 {'entropy': 0.9544340029249649,
  'gains': {'Administration': 0.10778574213673135,
   'Cooper_test': 0.4123254801911808,
   'MI': 0.4123254801911808,
   'Medical_certificate': 0.05816450858409041,
   'Medical_history': 0.1110025666410142,
   'Pull_up': 0.5151586937654048,
   'Push_up': 0.46137116296602854,
   'Shuttle_run': 0.46137116296602854,
   'Sit_up': 0.2818995498698638}})

In [ ]:
#checking the splitting attribute label
df['Pull_up']

0      >35
1      >35
2      >35
3     <=35
4     <=35
5     <=35
6      >35
7     <=35
8      >35
9      >35
10     >35
11     >35
12    <=35
13     >35
14     >35
15     >35
16     >35
17     >35
18    <=35
19     >35
20     >35
21     >35
22     >35
23     >35
24     >35
25     >35
26     >35
27     >35
28    <=35
29     >35
30     >35
31     >35
Name: Pull_up, dtype: object

In [ ]:
df[df['Pull_up']=='>35']

   Administration Medical_certificate  ...    MI Decision
0             Yes                 Fit  ...   >70   Passed
1             Yes                 Fit  ...   >70   Passed
2             Yes                 Fit  ...   >70   Passed
6             Yes                 Fit  ...   >70   Passed
8             Yes                 Fit  ...   >70   Passed
9              No                 Fit  ...   >70   Passed
10            Yes                 Fit  ...   >70   Failed
11            Yes                 Fit  ...  <=70   Failed
13            Yes                 Fit  ...   >70   Failed
14            Yes                 Fit  ...   >70   Passed
15            Yes                 Fit  ...   >70   Passed
16            Yes                 Fit  ...   >70   Passed
17            Yes                 Fit  ...   >70   Passed
19            Yes                 Fit  ...   >70   Passed
20            Yes             Not_Fit  ...   >70   Failed
21            Yes                 Fit  ...   >70   Passed
22            Yes                 Fit  ...   >70   Failed
23            Yes                 Fit  ...   >70   Passed
24            Yes                 Fit  ...   >70   Passed
25            Yes                 Fit  ...   >70   Passed
26            Yes                 Fit  ...   >70   Passed
27            Yes                 Fit  ...   >70   Passed
29            Yes             Not_Fit  ...   >70   Passed
30            Yes                 Fit  ...   >70   Passed
31            Yes                 Fit  ...   >70   Passed

[25 rows x 10 columns]

In [ ]:
df[df['Pull_up']=='<=35']

   Administration Medical_certificate  ...    MI Decision
3             Yes                 Fit  ...   >70   Failed
4             Yes                 Fit  ...   >70   Failed
5             Yes                 Fit  ...  <=70   Failed
7             Yes             Not_Fit  ...   >70   Failed
12            Yes                 Fit  ...  <=70   Failed
18            Yes                 Fit  ...  <=70   Failed
28            Yes                 Fit  ...  <=70   Failed

[7 rows x 10 columns]

In [ ]:
second_split = Training.findGains(df[df['Pull_up']=='>35'].drop(columns=['Pull_up']), c45)
second_split

{'entropy': 0.7219280948873623,
 'gains': {'Administration': 0.05437494060185534,
  'Cooper_test': 0.40408471472284996,
  'MI': 0.40408471472284996,
  'Medical_certificate': 0.07130156465234593,
  'Medical_history': 0.07130156465234593,
  'Push_up': 0.40408471472284996,
  'Shuttle_run': 0.5171552292567215,
  'Sit_up': 0.1421033872748304}}

In [ ]:
second_split2 = Training.findGains(df[df['Pull_up']=='<=35'].drop(columns=['Pull_up']), c45)
second_split2

{'entropy': 0.0,
 'gains': {'Administration': 0.0,
  'Cooper_test': 0.0,
  'MI': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Push_up': 0.0,
  'Shuttle_run': 0.0,
  'Sit_up': 0.0}}

In [ ]:
#First Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    return 'Need further research'
  else: return 'Failed'

###**Split 2**

In [ ]:
#Finding the gain ratio for second split
second_split = Training.findGains(df[df['Pull_up']=='>35'].drop(columns=['Pull_up']), c45)
second_split

{'entropy': 0.7219280948873623,
 'gains': {'Administration': 0.05437494060185534,
  'Cooper_test': 0.40408471472284996,
  'MI': 0.40408471472284996,
  'Medical_certificate': 0.07130156465234593,
  'Medical_history': 0.07130156465234593,
  'Push_up': 0.40408471472284996,
  'Shuttle_run': 0.5171552292567215,
  'Sit_up': 0.1421033872748304}}

In [ ]:
df['Shuttle_run']

0      >68
1      >68
2      >68
3      >68
4      >68
5      >68
6      >68
7     <=68
8      >68
9      >68
10     >68
11     >68
12    <=68
13    <=68
14     >68
15     >68
16     >68
17     >68
18    <=68
19     >68
20     >68
21     >68
22    <=68
23     >68
24     >68
25     >68
26     >68
27     >68
28    <=68
29     >68
30     >68
31     >68
Name: Shuttle_run, dtype: object

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate  ...    MI Decision
0             Yes                 Fit  ...   >70   Passed
1             Yes                 Fit  ...   >70   Passed
2             Yes                 Fit  ...   >70   Passed
6             Yes                 Fit  ...   >70   Passed
8             Yes                 Fit  ...   >70   Passed
9              No                 Fit  ...   >70   Passed
10            Yes                 Fit  ...   >70   Failed
11            Yes                 Fit  ...  <=70   Failed
14            Yes                 Fit  ...   >70   Passed
15            Yes                 Fit  ...   >70   Passed
16            Yes                 Fit  ...   >70   Passed
17            Yes                 Fit  ...   >70   Passed
19            Yes                 Fit  ...   >70   Passed
20            Yes             Not_Fit  ...   >70   Failed
21            Yes                 Fit  ...   >70   Passed
23            Yes                 Fit  ...   >70   Passed
24            Yes                 Fit  ...   >70   Passed
25            Yes                 Fit  ...   >70   Passed
26            Yes                 Fit  ...   >70   Passed
27            Yes                 Fit  ...   >70   Passed
29            Yes             Not_Fit  ...   >70   Passed
30            Yes                 Fit  ...   >70   Passed
31            Yes                 Fit  ...   >70   Passed

[23 rows x 10 columns]

In [ ]:
third_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'].drop(columns=['Pull_up', 'Shuttle_run']),c45)
third_split

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

{'entropy': 0.5586293734521992,
 'gains': {'Administration': 0.03479529770667036,
  'Cooper_test': 0.5357788717181237,
  'MI': 0.5357788717181237,
  'Medical_certificate': 0.134693212892727,
  'Medical_history': 0.134693212892727,
  'Push_up': 0.5357788717181237,
  'Sit_up': 0.1394032373575586}}

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='<=68']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
13            Yes                 Fit            None  ...        <=68  >70   Failed
22            Yes                 Fit            None  ...        <=68  >70   Failed

[2 rows x 10 columns]

In [ ]:
third_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='<=68'].drop(columns=['Pull_up', 'Shuttle_run']),c45)
third_split2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

{'entropy': 0.0,
 'gains': {'Administration': 0.0,
  'Cooper_test': 0.0,
  'MI': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Push_up': 0.0,
  'Sit_up': 0.0}}

In [ ]:
#Second Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      return 'Need further research'
    else: return 'Failed'
  else: return 'Failed'

###**Split 3**

In [ ]:
#Finding the gain ratio for third split
third_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'].drop(columns=['Pull_up', 'Shuttle_run']),c45)
third_split

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

{'entropy': 0.5586293734521992,
 'gains': {'Administration': 0.03479529770667036,
  'Cooper_test': 0.5357788717181237,
  'MI': 0.5357788717181237,
  'Medical_certificate': 0.134693212892727,
  'Medical_history': 0.134693212892727,
  'Push_up': 0.5357788717181237,
  'Sit_up': 0.1394032373575586}}

In [ ]:
df['Cooper_test']

0      >70
1      >70
2      >70
3      >70
4      >70
5      >70
6      >70
7     <=70
8      >70
9      >70
10     >70
11     >70
12    <=70
13     >70
14     >70
15     >70
16     >70
17     >70
18    <=70
19     >70
20    <=70
21     >70
22     >70
23     >70
24     >70
25     >70
26     >70
27     >70
28    <=70
29     >70
30     >70
31     >70
Name: Cooper_test, dtype: object

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate  ...    MI Decision
0             Yes                 Fit  ...   >70   Passed
1             Yes                 Fit  ...   >70   Passed
2             Yes                 Fit  ...   >70   Passed
6             Yes                 Fit  ...   >70   Passed
8             Yes                 Fit  ...   >70   Passed
9              No                 Fit  ...   >70   Passed
10            Yes                 Fit  ...   >70   Failed
11            Yes                 Fit  ...  <=70   Failed
14            Yes                 Fit  ...   >70   Passed
15            Yes                 Fit  ...   >70   Passed
16            Yes                 Fit  ...   >70   Passed
17            Yes                 Fit  ...   >70   Passed
19            Yes                 Fit  ...   >70   Passed
21            Yes                 Fit  ...   >70   Passed
23            Yes                 Fit  ...   >70   Passed
24            Yes                 Fit  ...   >70   Passed
25            Yes                 Fit  ...   >70   Passed
26            Yes                 Fit  ...   >70   Passed
27            Yes                 Fit  ...   >70   Passed
29            Yes             Not_Fit  ...   >70   Passed
30            Yes                 Fit  ...   >70   Passed
31            Yes                 Fit  ...   >70   Passed

[22 rows x 10 columns]

In [ ]:
fourth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'].drop(columns=['Pull_up','Cooper_test','Shuttle_run']),c45)
fourth_split

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

{'entropy': 0.4394969869215134,
 'gains': {'Administration': 0.024006590033997206,
  'MI': 0.6592165573983931,
  'Medical_certificate': 0.024006590033997206,
  'Medical_history': 0.024006590033997206,
  'Push_up': 0.0,
  'Sit_up': 0.05661826250868482}}

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='<=70']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
20            Yes             Not_Fit     U_Treatment  ...         >68  >70   Failed

[1 rows x 10 columns]

In [ ]:
fourth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='<=70'].drop(columns=['Pull_up','Cooper_test','Shuttle_run']),c45)
fourth_split2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

{'entropy': 0.0,
 'gains': {'Administration': 0.0,
  'MI': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Push_up': 0.0,
  'Sit_up': 0.0}}

In [ ]:
#Third Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        return 'Need further research'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'

###**Split 4**

In [ ]:
#Finding the gain ratio for fourth split
fourth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'].drop(columns=['Pull_up','Cooper_test','Shuttle_run']),c45)
fourth_split

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

{'entropy': 0.4394969869215134,
 'gains': {'Administration': 0.024006590033997206,
  'MI': 0.6592165573983931,
  'Medical_certificate': 0.024006590033997206,
  'Medical_history': 0.024006590033997206,
  'Push_up': 0.0,
  'Sit_up': 0.05661826250868482}}

In [ ]:
df['MI']

0      >70
1      >70
2      >70
3      >70
4      >70
5     <=70
6      >70
7      >70
8      >70
9      >70
10     >70
11    <=70
12    <=70
13     >70
14     >70
15     >70
16     >70
17     >70
18    <=70
19     >70
20     >70
21     >70
22     >70
23     >70
24     >70
25     >70
26     >70
27     >70
28    <=70
29     >70
30     >70
31     >70
Name: MI, dtype: object

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
0             Yes                 Fit            None  ...         >68  >70   Passed
1             Yes                 Fit            None  ...         >68  >70   Passed
2             Yes                 Fit            None  ...         >68  >70   Passed
6             Yes                 Fit            None  ...         >68  >70   Passed
8             Yes                 Fit            None  ...         >68  >70   Passed
9              No                 Fit            None  ...         >68  >70   Passed
10            Yes                 Fit            None  ...         >68  >70   Failed
14            Yes                 Fit     U_Treatment  ...         >68  >70   Passed
15            Yes                 Fit            None  ...         >68  >70   Passed
16            Yes                 Fit            None  ...         >68  >70   Passed
17            Yes                 Fit            None  ...         >68  >70   Passed
19            Yes                 Fit            None  ...         >68  >70   Passed
21            Yes                 Fit            None  ...         >68  >70   Passed
23            Yes                 Fit            None  ...         >68  >70   Passed
24            Yes                 Fit            None  ...         >68  >70   Passed
25            Yes                 Fit            None  ...         >68  >70   Passed
26            Yes                 Fit            None  ...         >68  >70   Passed
27            Yes                 Fit            None  ...         >68  >70   Passed
29            Yes             Not_Fit            None  ...         >68  >70   Passed
30            Yes                 Fit            None  ...         >68  >70   Passed
31            Yes                 Fit            None  ...         >68  >70   Passed

[21 rows x 10 columns]

In [ ]:
fifth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Push_up']),c45)
fifth_split

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

{'entropy': 0.2761954276479391,
 'gains': {'Administration': 0.012441990441703604,
  'Medical_certificate': 0.012441990441703604,
  'Medical_history': 0.012441990441703604,
  'Sit_up': 0.17319865388722194}}

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='<=70']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate  ...    MI Decision
11            Yes                 Fit  ...  <=70   Failed

[1 rows x 10 columns]

In [ ]:
fifth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='<=70'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Push_up']),c45)
fifth_split2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

{'entropy': 0.0,
 'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0,
  'Sit_up': 0.0}}

In [ ]:
#Fourth Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        if MI>70:
          return 'Need further research'
        else: return 'Failed'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'

###**Split 5**

In [ ]:
#Finding the gain ratio for fifth split
fifth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Push_up']),c45)
fifth_split

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

{'entropy': 0.2761954276479391,
 'gains': {'Administration': 0.012441990441703604,
  'Medical_certificate': 0.012441990441703604,
  'Medical_history': 0.012441990441703604,
  'Sit_up': 0.17319865388722194}}

In [ ]:
df['Sit_up']

0      >78
1      >78
2     <=78
3     <=78
4     <=78
5      >78
6     <=78
7     <=78
8      >78
9      >78
10    <=78
11     >78
12    <=78
13     >78
14     >78
15     >78
16     >78
17     >78
18    <=78
19     >78
20    <=78
21     >78
22    <=78
23     >78
24     >78
25     >78
26     >78
27     >78
28    <=78
29    <=78
30     >78
31     >78
Name: Sit_up, dtype: object

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='>78']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
0             Yes                 Fit            None  ...         >68  >70   Passed
1             Yes                 Fit            None  ...         >68  >70   Passed
8             Yes                 Fit            None  ...         >68  >70   Passed
9              No                 Fit            None  ...         >68  >70   Passed
14            Yes                 Fit     U_Treatment  ...         >68  >70   Passed
15            Yes                 Fit            None  ...         >68  >70   Passed
16            Yes                 Fit            None  ...         >68  >70   Passed
17            Yes                 Fit            None  ...         >68  >70   Passed
19            Yes                 Fit            None  ...         >68  >70   Passed
21            Yes                 Fit            None  ...         >68  >70   Passed
23            Yes                 Fit            None  ...         >68  >70   Passed
24            Yes                 Fit            None  ...         >68  >70   Passed
25            Yes                 Fit            None  ...         >68  >70   Passed
26            Yes                 Fit            None  ...         >68  >70   Passed
27            Yes                 Fit            None  ...         >68  >70   Passed
30            Yes                 Fit            None  ...         >68  >70   Passed
31            Yes                 Fit            None  ...         >68  >70   Passed

[17 rows x 10 columns]

In [ ]:
sixth_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='>78'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Push_up']),c45)
sixth_split

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

{'entropy': 0.0,
 'gains': {'Administration': 0.0,
  'Medical_certificate': 0.0,
  'Medical_history': 0.0}}

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
2             Yes                 Fit            None  ...         >68  >70   Passed
6             Yes                 Fit            None  ...         >68  >70   Passed
10            Yes                 Fit            None  ...         >68  >70   Failed
29            Yes             Not_Fit            None  ...         >68  >70   Passed

[4 rows x 10 columns]

In [ ]:
sixth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Push_up']),c45)
sixth_split2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

{'entropy': 0.8112781244591328,
 'gains': {'Administration': 0.0,
  'Medical_certificate': 0.15106563978903303,
  'Medical_history': 0.0}}

In [ ]:
#Fifth Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        if MI>70:
          if Sit_up>78:
            return 'Passed'
          else: return 'Need further research'
        else: return 'Failed'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'

###**Split 6**

In [ ]:
#Finding the gain ratio for sixth split
sixth_split2 = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Push_up']),c45)
sixth_split2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

{'entropy': 0.8112781244591328,
 'gains': {'Administration': 0.0,
  'Medical_certificate': 0.15106563978903303,
  'Medical_history': 0.0}}

In [ ]:
df['Medical_certificate']

0         Fit
1         Fit
2         Fit
3         Fit
4         Fit
5         Fit
6         Fit
7     Not_Fit
8         Fit
9         Fit
10        Fit
11        Fit
12        Fit
13        Fit
14        Fit
15        Fit
16        Fit
17        Fit
18        Fit
19        Fit
20    Not_Fit
21        Fit
22        Fit
23        Fit
24        Fit
25        Fit
26        Fit
27        Fit
28        Fit
29    Not_Fit
30        Fit
31        Fit
Name: Medical_certificate, dtype: object

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
2             Yes                 Fit            None  ...         >68  >70   Passed
6             Yes                 Fit            None  ...         >68  >70   Passed
10            Yes                 Fit            None  ...         >68  >70   Failed

[3 rows x 10 columns]

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Not_Fit']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
29            Yes             Not_Fit            None  ...         >68  >70   Passed

[1 rows x 10 columns]

In [ ]:
#Sixth Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        if MI>70:
          if Sit_up>78:
            return 'Passed'
          else: 
            if Medical_certificate=='Fit':
              return 'Need further research'
            elif Medical_certificate=='Not_Fit':
              return 'Passed'
        else: return 'Failed'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'

###**Split 7**

In [ ]:
#Finding the gain ratio for seventh split
seventh_split = Training.findGains(df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'].drop(columns=['Pull_up','Shuttle_run','MI','Cooper_test','Sit_up','Medical_certificate']),c45)
seventh_split

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

{'entropy': 0.9182958340544896,
 'gains': {'Administration': 0.0, 'Medical_history': 0.0, 'Push_up': 0.0}}

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Administration']=='Yes']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
2             Yes                 Fit            None  ...         >68  >70   Passed
6             Yes                 Fit            None  ...         >68  >70   Passed
10            Yes                 Fit            None  ...         >68  >70   Failed

[3 rows x 10 columns]

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Administration']=='No']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Medical_history']=='None']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
2             Yes                 Fit            None  ...         >68  >70   Passed
6             Yes                 Fit            None  ...         >68  >70   Passed
10            Yes                 Fit            None  ...         >68  >70   Failed

[3 rows x 10 columns]

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Medical_history']=='U_Treatment']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Push_up']=='>69']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

   Administration Medical_certificate Medical_history  ... Shuttle_run   MI Decision
2             Yes                 Fit            None  ...         >68  >70   Passed
6             Yes                 Fit            None  ...         >68  >70   Passed
10            Yes                 Fit            None  ...         >68  >70   Failed

[3 rows x 10 columns]

In [ ]:
df[df['Pull_up']=='>35'][df['Shuttle_run']=='>68'][df['Cooper_test']=='>70'][df['MI']=='>70'][df['Sit_up']=='<=78'][df['Medical_certificate']=='Fit'][df['Push_up']=='<=69']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

Empty DataFrame
Columns: [Administration, Medical_certificate, Medical_history, Cooper_test, Push_up, Sit_up, Pull_up, Shuttle_run, MI, Decision]
Index: []

In [ ]:
#Final Construction
def findDecision(Administration, Medical_certificate, Medical_history, Cooper_run, Push_up, Sit_up, Pull_up, Shuttle_run, MI):
  if Pull_up>35:
    if Shuttle_run>68:
      if Cooper_run>70:
        if MI>70:
          if Sit_up>78:
            return 'Passed'
          else: 
            if Medical_certificate=='Fit':
              return 'Unable to make decision, please consider the recruits Administration, Medical history, and Push up results'
            elif Medical_certificate=='Not_Fit':
              return 'Passed'
        else: return 'Failed'
      else: return 'Failed'
    else: return 'Failed'
  else: return 'Failed'